<div id="page-headline">
<div id="page-headline-breadcrums">
</div>
<div id="page-headline-text">Pagina niet gevonden</div>
</div>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="content-section-2col">

<tbody><tr><td colspan="5" style="height: 4px;"></td></tr>

<tr>

	<td rowspan="2" style="width: 8px;"></td>

	<td valign="top" style="width: 740px;">

		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tbody><tr><td colspan="2" style="padding-bottom: 3px;"></td></tr>
			<tr>

				<td align="left" valign="top" style="width: 430px; height: 400px;" class="habboPage-col">
<div class="v3box yellow">
<div class="v3box-top"><h3>Pagina niet gevonden!</h3></div>
<div class="v3box-content">
	<div class="v3box-body">

<img vspace="0" hspace="10" border="0" align="right" src="/c_images/content/maintenance.gif" id="galleryImage" alt="maintenance.gif"><span style="font-weight: bold;">OEPS!</span><br><p><b>De pagina die je wilt bezoeken, die, euh - hoe kunnen we het nou aardig zeggen - die bestaat niet. In ieder geval niet binnen de virtuele hekken van Habbo Hotel...</b></p>


		<div class="clear"></div>
	</div>
</div>
<div class="v3box-bottom"><div></div></div>
</div>
				</td>
				<td align="left" valign="top" style="width: 310px; height: 400px;" class="habboPage-col rightmost">



<div class="v3box yellow">
<div class="v3box-top"><h3>Pagina niet gevonden? </h3></div>
<div class="v3box-content">
	<div class="v3box-body">

<p><b>Hoe kon dat nou gebeuren? </b><br>
1) Je hebt een foute url ingetypt. Ga dan terug naar de <a href="/web/20071008003650/http://www.habbohotel.nl/">homepage</a>, en doe het NOOIT MEER! :P<br>
2) Wij hebben een fout gemaakt. Kan gebeuren. Ga dan terug naar de <a href="/web/20071008003650/http://www.habbohotel.nl/">homepage</a>, probeer het opnieuw - en vergeef ons...<br>
3) Er is een technische fout waardoor deze pagina niet beschikbaar is. Bobba happens...</p><p><br></p>

<p>Je kunt natuurlijk de pagina verversen tot de zon achter het hotel ondergaat, maar je kunt ook:</p>
<p>
<a href="/web/20071008003650/http://www.habbo.nl/client.action">Het hotel in &gt;&gt;</a><br>
<a href="/web/20071008003650/http://www.habbo.nl/">Opnieuw beginnen: naar de homepage &gt;&gt;</a><br>
<a href="/web/20071008003650/http://www.habbo.nl/community/" target="_self">Lezen wat de andere Habbo's ervan vinden op de Community Pages &gt;&gt;</a><br>
<a href="/web/20071008003650/http://www.habbo.nl/help/habbo_way.html" target="_self">Een leermoment inbouwen - Naar de Habbo Regels &gt;&gt;</a>
</p>

<p>*zwaait*</p>
		<div class="clear"></div>
	</div>
</div>
<div class="v3box-bottom"><div></div></div>
</div>
				</td>

			</tr>
		</tbody></table>

	</td>

	<td rowspan="2" style="width: 4px;"></td>

	<td rowspan="2" valign="top" style="width: 176px;">
<div id="ad_sidebar">

<div class="ad-scale ad160">
<table>
	<tbody><tr><td class="ad-header-tl"></td><td class="ad-header-t"></td><td class="ad-header-tr"></td></tr>
	<tr><td class="ad-header-ml"></td><td class="ad-header-m"><h5>Advertentie</h5></td><td class="ad-header-mr"></td></tr>
	<tr><td class="ad-content-ml"></td><td class="ad-content-m" align="center" valign="top"></td><td class="ad-content-mr"></td></tr>
	<tr><td class="ad-content-bl"></td>	<td class="ad-content-b"></td><td class="ad-content-br"></td></tr>
</tbody></table>
</div>



</div>		</td>
</tr>

</tbody></table>

<br style="clear: both;">